name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10.12"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          
      # Install Taskwarrior  
      - name: Create Taskwarrior configuration file
        run: echo "data.location=~/.task" > ~/.taskrc
        
      # Install Taskwarrior
      - name: Install Taskwarrior
        run: sudo apt-get update && sudo apt-get install taskwarrior

      # Install dependencies and run tests
      - name: Install dependencies and run tests
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pytest

      # Generate Coverage Report (if applicable)
      - name: Generate Coverage Report
        run: |
          coverage report -m
